name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install and run AWS CLI
        shell: bash
        run: |
          awsinstallrc=/tmp/aws-install-rc
          echo 'function myawscli() {
            docker run --rm -v $HOME/.aws:/root/.aws -v $(pwd):/aws public.ecr.aws/aws-cli/aws-cli@sha256:06f95828509d83f5899d373e054ab1ed91dc84b03cf665f755b668cbaf38b822 ${@}
          }' > $awsinstallrc
          source $awsinstallrc
          myawscli --version
      - name: Run AWS CLI
        shell: bash
        run: |
          source /tmp/aws-install-rc
          myawscli help
          something=$(myawscli --version)
          echo $something
